config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'top#index'
  resources :users,only: [:edit, :update]
  resources :contents, :switch,:switch2,:switch3,:switch4,:switch5,:switch6,:switch7,:switch8,:switch9,only: [:index,:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { maximum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
  # before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  def index
  end

  def new
  end
end

app/controllers/switch2_controller.rb
class Switch2Controller < ApplicationController
  def index
  end

  def new
  end
end

app/controllers/switch3_controller.rb
class Switch3Controller < ApplicationController
  def index
  end

  def new
  end
end

app/controllers/switch4_controller.rb
class Switch4Controller < ApplicationController
  def index
  end

  def new
  end
end

app/controllers/switch5_controller.rb
class Switch5Controller < ApplicationController
  def index
  end

  def new
  end
end

app/controllers/switch6_controller.rb
class Switch6Controller < ApplicationController
  def index
  end

  def new
  end
end

app/controllers/switch7_controller.rb
class Switch7Controller < ApplicationController
  def index
  end

  def new
  end
end

app/controllers/switch8_controller.rb
class Switch8Controller < ApplicationController
  def index
  end

  def new
  end
end

app/controllers/switch9_controller.rb
class Switch9Controller < ApplicationController
  def index
  end

  def new
  end
end

app/controllers/switch_controller.rb
class SwitchController < ApplicationController
  def index
  end

  def new
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contents/_main.html.haml
.main-content
  .main-content__header
    .main-content__header__guest
      今回のゲスト
    .LikesIcon
      %i.far.fa-star.LikesIcon-fa-star
        いいね!!
  
  .main-content__center
    .main-content__center__left
      = audio_tag "情熱大陸 OP.mp3",id:"audio"
      .main-content__center__left__name
        本田 圭佑
      .main-content__center__left__work
        サッカー選手
    .main-content__center__image
      =link_to image_tag("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcToOkcVz7XQUtsReRS_0JO38fmF6f7PSm69si1QN_FgwyBJjG-l", width:"500", height:"350", id:"image"),"https://matome.naver.jp/odai/2133950543504842601"
      .text
        ☝︎名言集は画像をClick!!

  .footer
    .footer__message
      「成功」に捉われるな、「成長」に捉われろ!!

app/views/contents/_main__header.html.haml
.main-content
  .main-content__header
    .main-content__header__guest
      今回のゲスト
    .LikesIcon
      %i.far.fa-star.LikesIcon-fa-star
        いいね!!

app/views/contents/_side.html.haml
.side
  .side__logo
    = image_tag("logo.png", size: "130x130",class:"side__logo__netulogo")
  .side__center
    = button_tag 'START', type: 'button', id:"button",class:"side__center__startbtn"
  .side__bottom
    =link_to root_path, class:"side__btn side__btn--top" do
      = icon('fas','step-backward')
      TOPへ戻る
    =link_to new_user_registration_path , class:"side__btn side__btn--user" do
      = icon('fas','plus-square')
      新規登録
    = link_to "https://www.facebook.com/", class: "side__btn side__btn--facebook" do
      = icon('fab', 'facebook-square')
      Facebook
    = link_to "https://twitter.com/", class: "side__btn side__btn--twitter" do
      = icon('fab', 'twitter')
      Twitter
    = link_to "https://www.instagram.com/", class: "side__btn side__btn--instagram" do
      = icon('fab', 'instagram')
      Instagram

app/views/contents/index.html.haml
.wrapper
  =render "main"
  =render "side"

app/views/contents/new.html.haml
.main-content
  .main-content__header
    .main-content__header__guest
      今回のゲスト
    .LikesIcon
      %i.far.fa-star.LikesIcon-fa-star
        いいね!!

  .main-content__center
    .main-content__center__left
      = audio_tag "情熱大陸 OP.mp3",id:"audio"
      .main-content__center__left__name
        イチロー
      .main-content__center__left__work
        野球選手
    .main-content__center__image
      =link_to image_tag("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQC9kNFHMKzVJh2M0Gfhh0sau1UdqE8EpjZmiFwM47qQm-69XaR", width:"500", height:"350", id:"image"),"https://matome.naver.jp/odai/2133414522447477501"
      .text
        ☝︎名言集は画像をClick!!

  .footer
    .footer__message
      小さな事の積み重ねがとんでもない所に行くただ一つの道。

=render "side"

app/views/switch/index.html.haml
.wrapper
  .main-content
    .main-content__header
      =render "contents/main__header"
    
    .main-content__center
      .main-content__center__left
        = audio_tag "情熱大陸 OP.mp3",id:"audio"
        .main-content__center__left__name
          Steve Jobs
        .main-content__center__left__work
          Apple創業者
      .main-content__center__image
        =link_to image_tag("https://i0.wp.com/meigen-ijin.com/wp/wp-content/uploads/2013/06/stevejobs400.jpg?resize=400%2C260&ssl=1", width:"500", height:"350", id:"image"),"https://matome.naver.jp/odai/2156643567763007801"
        .text
          ☝︎名言集は画像をClick!! 

    .footer
      .footer__message
        Connecting The Dots　〜点と点は後から繋がっていくのです〜

  =render "contents/side"

app/views/switch2/index.html.haml
.wrapper
  .main-content
    .main-content__header
      =render "contents/main__header"
    
    .main-content__center
      .main-content__center__left
        = audio_tag "情熱大陸 OP.mp3",id:"audio"
        .main-content__center__left__name
          真子 就有
        .main-content__center__left__work
          起業家
      .main-content__center__image
        =link_to image_tag("https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRAfl0rEfbQCx8WaqNdTI_CzkKcm-VUzDqol54SKx3SEKxwTsI6", width:"500", height:"350", id:"image"),"https://taku-info.com/makonari-quotes/"
        .text
          ☝︎名言集は画像をClick!!

    .footer
      .footer__message
        「好きな事をやる」のではなく「嫌じゃない事ならやってみる」

  =render "contents/side"

app/views/switch2/new.html.haml
.wrapper
  .main-content
    .main-content__header
      =render "contents/main__header"
    
    .main-content__center
      .main-content__center__left
        = audio_tag "情熱大陸 OP.mp3",id:"audio"
        .main-content__center__left__name
          ﾏｲｹﾙ・ｼﾞｮｰﾀﾞﾝ
        .main-content__center__left__work
          NBAプレイヤー
      .main-content__center__image
        =link_to image_tag("https://meigen.club/wp-content/uploads/thumb_michael_jordan-11.jpg", width:"500", height:"350", id:"image"),"https://matome.naver.jp/odai/2131616827716144501"
        .text
          ☝︎名言集は画像をClick!!

    .footer
      .footer__message
        人生で何度も何度も失敗してきた。だから私は成功したんだ。

  =render "contents/side"

app/views/switch3/new.html.haml
.wrapper
  .main-content
    .main-content__header
      =render "contents/main__header"
    
    .main-content__center
      .main-content__center__left
        = audio_tag "情熱大陸 OP.mp3",id:"audio"
        .main-content__center__left__name
          ボブ・マーリー
        .main-content__center__left__work
          レゲエミュージシャン
      .main-content__center__image
        =link_to image_tag("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_OL8cxwsu6qk9BmIStJgySGUnvrJoeiy5MH_t4B4R5vwOTC8Yqw&s", width:"500", height:"350", id:"image"),"https://matome.naver.jp/odai/2143692911351333101"
        .text
          ☝︎名言集は画像をClick!!

    .footer
      .footer__message
        自分の生きる人生を愛せ。自分の愛する人生を生きろ。

  =render "contents/side"

app/views/switch5/index.html.haml
.wrapper
  .main-content
    .main-content__header
      =render "contents/main__header"
    
    .main-content__center
      .main-content__center__left
        = audio_tag "情熱大陸 OP.mp3",id:"audio"
        .main-content__center__left__name
          坂本 龍馬
        .main-content__center__left__work
          幕末の志士
      .main-content__center__image
        =link_to image_tag("https://hinotorifugetsu.com/wp-content/uploads/2018/12/ryoma-1.png", width:"500", height:"350", id:"image"),"https://matome.naver.jp/odai/2147938229367268601"
        .text
          ☝︎名言集は画像をClick!!

    .footer
      .footer__message
        おれは落胆するよりも、次の策を考えるほうの人間だ。

  =render "contents/side"

app/views/switch5/new.html.haml
.wrapper
  .main-content
    .main-content__header
      =render "contents/main__header"
    
    .main-content__center
      .main-content__center__left
        = audio_tag "情熱大陸 OP.mp3",id:"audio"
        .main-content__center__left__name
          織田 信長
        .main-content__center__left__work
          戦国武将
      .main-content__center__image
        =link_to image_tag("https://mk0sekainorekisr2s2b.kinstacdn.com/wp-content/uploads/2018/04/Oda-Nobunaga.jpg", width:"500", height:"350", id:"image"),"https://matome.naver.jp/odai/2152423308424018501"
        .text
          ☝︎名言集は画像をClick!!

    .footer
      .footer__message
        理想を持ち信念に生きよ。それを見失った者は戦う前から負けている。

  =render "contents/side"

app/views/switch6/index.html.haml
.wrapper
  .main-content
    .main-content__header
      =render "contents/main__header"
    
    .main-content__center
      .main-content__center__left
        = audio_tag "情熱大陸 OP.mp3",id:"audio"
        .main-content__center__left__name
          ﾄｰﾏｽ・ｴｼﾞｿﾝ
        .main-content__center__left__work
          発明家・起業家
      .main-content__center__image
        =link_to image_tag("https://kohkira.com/wp-content/uploads/2017/01/thomas-alva-edison-67763_640-1.jpg", width:"500", height:"350", id:"image"),"https://matome.naver.jp/odai/2147903059338929601"
        .text
          ☝︎名言集は画像をClick!!

    .footer
      .footer__message
        失敗ではなく、ただ1万通りの上手くいかない方法を見つけただけだ。

  =render "contents/side"

app/views/switch8/index.html.haml
.wrapper
  .main-content
    .main-content__header
      =render "contents/main__header"
    
    .main-content__center
      .main-content__center__left
        = audio_tag "情熱大陸 OP.mp3",id:"audio"
        .main-content__center__left__name
          錦織 圭
        .main-content__center__left__work
          テニスプレイヤー
      .main-content__center__image
        =link_to image_tag("http://nisikorikeisdraw.com/wp-content/uploads/2017/05/01-4.jpg", width:"500", height:"350", id:"image"),"https://matome.naver.jp/odai/2153139237394476501?page=2"
        .text
          ☝︎名言集は画像をClick!!

    .footer
      .footer__message
        誰かを越す誰かに抜かれるとかではなく、自分ができる最大の努力をする

  =render "contents/side"

app/views/top/_top_main.html.haml
.main
  .main__top__header
    .main__top__header__title
      Motivation
    .main__top__header__subtitle
      🔘Switch
      
    .main__top__header__menu
      - if user_signed_in?
        =link_to edit_user_path(current_user) , class:"main__top__header__menu__btn" do
          =icon('fas', 'cog')
          = current_user.name
          
        =link_to destroy_user_session_path, method: :delete,  class:"main__top__header__menu__btn" do
          =icon('fas', 'sign-out-alt')
          ログアウト

      - else
        =link_to new_user_registration_path, class:"main__top__header__menu__btn" do
          = icon('fas','plus-square')
          ユーザー登録
    
        =link_to new_user_session_path, class:"main__top__header__menu__btn" do
          = icon('fas','sign-in-alt')
          ログイン

    .form-group
      %input#keyword.form-control{placeholder: "好きな偉人を検索できます。", type:"text"}
      %button#submit.btn{type: "button"}
        = icon('fas', 'search', class:"search")
    %ul#list

      
      
    .main__top__header__icon
      = link_to "https://www.facebook.com/", class: "main__top__header__icon--facebook" do
        = icon('fab', 'facebook-square')
        
      = link_to "https://twitter.com/", class: "main__top__header__icon--twitter" do
        = icon('fab', 'twitter')
        
      = link_to "https://www.instagram.com/", class: "main__top__header__icon--instagram" do
        = icon('fab', 'instagram')
        
  .main__top__images
    = video_tag "video.mp4", autoplay: true, poster:"run.jpg", muted: true,  loop:true, preload: true ,width: "1200", height:"580" ,class: "main__top__images__video"
    .accordion
      著名人一覧
      %ul.menu
        - if user_signed_in?
          %li.menu__item
            .menu__item__link.js-menu__item__link スポーツ選手
            %ul.submenu
              %li.submenu__item
                = link_to "本田 圭佑" ,contents_path
              %li.submenu__item
                = link_to "イチロー" ,new_content_path
              %li.submenu__item
                = link_to "マイケル・ジョーダン" ,new_switch2_path
              %li.submenu__item
                = link_to "錦織 圭" ,switch8_index_path
              %li.submenu__item
                = link_to "為末 大" ,new_switch9_path
                
          %li.menu__item 
            .menu__item__link.js-menu__item__link 芸能・音楽
            %ul.submenu
              %li.submenu__item
                = link_to "堀江 貴文", new_switch7_path
              %li.submenu__item
                = link_to "GACKT", switch3_index_path
              %li.submenu__item
                = link_to "島田 紳助", switch4_index_path
              %li.submenu__item
                = link_to "美輪 明宏", switch9_index_path
              %li.submenu__item
                = link_to "ボブ・マーリー", new_switch3_path


          %li.menu__item 
            .menu__item__link.js-menu__item__link 実業家
            %ul.submenu
              %li.submenu__item
                = link_to "スティーブ・ジョブズ" ,switch_index_path
              %li.submenu__item
                = link_to "稲盛 和夫" ,new_switch_path
              %li.submenu__item
                = link_to "孫 正義" ,new_switch8_path
              %li.submenu__item
                = link_to "マコなり社長" ,switch2_index_path


          %li.menu__item 
            .menu__item__link.js-menu__item__link 武将・幕末
            %ul.submenu
              %li.submenu__item
                = link_to "武田 信玄" ,new_switch4_path
              %li.submenu__item
                = link_to "織田 信長" ,new_switch5_path
              %li.submenu__item
                = link_to "坂本 龍馬" ,switch5_index_path
          
          %li.menu__item 
            .menu__item__link.js-menu__item__link 学者・発明家
            %ul.submenu
              %li.submenu__item
                = link_to "トーマス・エジソン" ,switch6_index_path
              %li.submenu__item
                = link_to "ピーター・ドラッガー" ,new_switch6_path
              %li.submenu__item
                = link_to "ダーウィン" ,switch7_index_path

        - else
          %ul.menu
            %li.menu__item
              .menu__item__link.js-menu__item__link スポーツ選手
              %ul.submenu
                %li.submenu__item
                  = link_to "本田 圭佑" ,contents_path
                %li.submenu__item
                  = link_to "イチロー" ,new_content_path
                %li.submenu__item
                  = link_to "？" ,new_user_registration_path
                %li.submenu__item
                  = link_to "？" ,new_user_registration_path
                %li.submenu__item
                  = link_to "？" ,new_user_registration_path
            
            %li.menu__item 
              .menu__item__link.js-menu__item__link 芸能・音楽
              %ul.submenu
                %li.submenu__item
                  = link_to "堀江 貴文", new_switch7_path
                %li.submenu__item
                  = link_to "GACKT", switch3_index_path
                %li.submenu__item
                  = link_to "？" ,new_user_registration_path
                %li.submenu__item
                  = link_to "？" ,new_user_registration_path
                %li.submenu__item
                  = link_to "？" ,new_user_registration_path

            %li.menu__item 
              .menu__item__link.js-menu__item__link 実業家
              %ul.submenu
                %li.submenu__item
                  = link_to "スティーブ・ジョブズ" ,switch_index_path
                %li.submenu__item
                  = link_to "稲盛 和夫" ,new_switch_path
                %li.submenu__item
                  = link_to "？" ,new_user_registration_path
                %li.submenu__item
                  = link_to "？" ,new_user_registration_path
                %li.submenu__item
                  = link_to "？" ,new_user_registration_path

            %li.menu__item 
              .menu__item__link.js-menu__item__link 武将・幕末
              %ul.submenu
                %li.submenu__item
                  = link_to "武田 信玄" ,new_switch4_path
                %li.submenu__item
                  = link_to "？" ,new_user_registration_path
                %li.submenu__item
                  = link_to "？" ,new_user_registration_path
            
            %li.menu__item 
              .menu__item__link.js-menu__item__link 学者・発明家
              %ul.submenu
                %li.submenu__item
                  = link_to "トーマス・エジソン" ,switch6_index_path
                %li.submenu__item
                  = link_to "?" ,new_user_registration_path 
                %li.submenu__item
                  = link_to "?" ,new_user_registration_path 

app/views/top/index.html.haml
.wrapper
  =render 'top_main'

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      -# %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete,class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'